server:
  port: 8080

spring:
  application:
    name: oauth-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.empresa.com.br/auth/realms/meu-relm
          jwk-set-uri: http://auth.empresa.com.br/auth/realms/meu-relm/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://auth.empresa.com.br/auth
  realm: fachesf
  client-id: client-id-aqui-pegue-no-keycloak
  client-secret: client-secret-aqui-pegue-no-keycloak
