server:
  port: 8080

spring:
  application:
    name: oauth-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://lab.fachesf.com.br:11111/auth/realms/fachesf
          jwk-set-uri: http://lab.fachesf.com.br:11111/auth/realms/fachesf/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://lab.fachesf.com.br:11111/auth
  realm: fachesf
  client-id: oauth-service
  client-secret: ll3pJAyxcCBfpDf5GUf1BYMzK6uOi135